"""CompShare execution driver for maintainer GPU evaluation."""

from dftworld_bench.hpc.drivers.compshare.cli import (
    CommandPlan,
    CliResult,
    CompShareCli,
    CompShareCliCapacityError,
    CompShareCliError,
    CompShareCliJsonError,
    CompShareCliNotFoundError,
    FakeCompShareCliRunner,
    InstanceCreateSpec,
    build_instance_create_argv,
    build_instance_create_command,
    build_instance_create_plan,
    plan_instance_create,
)
from dftworld_bench.hpc.drivers.compshare.driver import (
    CompShareDriver,
    CompShareDriverError,
)
from dftworld_bench.hpc.drivers.compshare.instance_manager import (
    BudgetConfig,
    CompShareBudgetExceededError,
    CompShareManagerError,
    CompShareOrphanError,
    RunScopedInstanceManager,
)
from dftworld_bench.hpc.drivers.compshare.policy import (
    SAFE_DELETED_STATES,
    extract_verified_instance_id,
    instance_requires_cleanup,
    make_ownership_marker,
    matches_ownership_marker,
    is_canonical_ownership_marker,
)
from dftworld_bench.hpc.site_profile import CompShareBudgetPolicy
from dftworld_bench.hpc.drivers.compshare.state import (
    AccountScopeLock,
    AccountScopeLockTimeout,
    AccountScopeLockTimeoutError,
    CompSharePolicyError,
    CompShareStateError,
    PersistentAccountScopeLock,
    account_scope_digest,
    account_scope_hash,
    account_scope_material,
    assert_account_capacity,
    stable_account_scope_hash,
)

__all__ = [
    "CliResult",
    "CommandPlan",
    "CompShareCli",
    "CompShareCliCapacityError",
    "CompShareCliError",
    "CompShareCliJsonError",
    "CompShareCliNotFoundError",
    "FakeCompShareCliRunner",
    "InstanceCreateSpec",
    "build_instance_create_argv",
    "build_instance_create_command",
    "build_instance_create_plan",
    "plan_instance_create",
    "CompShareDriver",
    "CompShareDriverError",
    "BudgetConfig",
    "CompShareBudgetExceededError",
    "CompShareManagerError",
    "CompShareOrphanError",
    "RunScopedInstanceManager",
    "SAFE_DELETED_STATES",
    "instance_requires_cleanup",
    "make_ownership_marker",
    "matches_ownership_marker",
    "extract_verified_instance_id",
    "is_canonical_ownership_marker",
    "CompShareBudgetPolicy",
    "AccountScopeLock",
    "AccountScopeLockTimeout",
    "AccountScopeLockTimeoutError",
    "CompSharePolicyError",
    "CompShareStateError",
    "PersistentAccountScopeLock",
    "account_scope_digest",
    "account_scope_hash",
    "account_scope_material",
    "assert_account_capacity",
    "stable_account_scope_hash",
]
