#!/bin/bash
# ============================================================================
# DeepMD training runner (per-model), container-adapted.
#   dp train input.json  ->  touch train.done  ->  dp freeze  ->  dp compress
# Idempotent via train.done; freeze/compress are cheap and re-run safely.
# input.json is generated by the omb combo with @SEED@/@TRAIN_STEPS@/@DECAY_STEPS@
# /@NUMB_TEST@/@DISP_FREQ@/@SAVE_FREQ@/@DP_DATASET@ substituted.
# The generated .slurm header sources solution/expert/env.sh, so `dp` is on PATH.
# ============================================================================
set -e

[ -f train.done ] || {
    dp train input.json
    touch train.done
}

dp freeze -o frozen_model.pb
dp compress -i frozen_model.pb -o compress.pb
