FROM dftworld-base-deepmd
COPY training_data /app/data/training_data
COPY validation_data /app/data/validation_data
COPY input_template.json /app/input_template.json
COPY data_geometry.txt /app/data_geometry.txt
