"""Public compute-qualification CLI zero-orphan checks.

These tests invoke ``cli.main`` with a real v2 receipt and the official
CLI-shaped FakeCompShare runner.  The only live-cloud state varied here is
the provider's account-list record; the production checker must classify
every non-deleted status as still requiring cleanup.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

import pytest

from dftworld_bench import cli
from dftworld_bench.hpc.drivers.compshare import (
    FakeCompShareCliRunner,
    make_ownership_marker,
)
from dftworld_bench.hpc.drivers.compshare import cli as compshare_cli_module
from dftworld_bench.experiments import compute_profile_qualification as cpq


def _cli_fixture(tmp_path: Path) -> tuple[Path, Path, Path, Path, Path]:
    """Materialize a valid v2 receipt and explicit CLI trust inputs."""
    from tests.hpc.test_c10_public_integration import run_public_c10_lifecycle

    result = run_public_c10_lifecycle(tmp_path)
    receipt = result["receipt"]

    # Re-seal the Layer-2 body with a key whose public half is explicitly
    # written to the trust store below.  Site receipts remain the real signed
    # artifacts generated by the C10 public lifecycle.
    compute_private, compute_public = cpq.generate_ed25519_key_pair()
    body = {
        key: value
        for key, value in receipt.items()
        if key not in {"digest", "signature"}
    }
    body["digest"] = cpq.compute_receipt_digest(body)
    body["signature"] = cpq.sign_compute_profile_receipt(body, compute_private)
    receipt_path = tmp_path / "compute-profile-receipt.json"
    receipt_path.write_text(
        json.dumps(body, sort_keys=True, indent=2) + "\n", encoding="utf-8"
    )

    profile_path = tmp_path / "compute-profile.json"
    registry_path = tmp_path / "trusted-site-profiles"
    registry_path.mkdir()
    for site_id in ("compshare-cpu", "compshare-gpu"):
        shutil.copyfile(
            tmp_path / f"{site_id}-site-profile.json",
            registry_path / f"{site_id}.json",
        )

    site_key = result["catalog"].trust_store.get_key("compshare-site-v1")
    assert site_key is not None
    trust_store_path = tmp_path / "qualification-trust.toml"
    trust_store_path.write_text(
        "\n".join(
            (
                "[keys.compshare-site-v1]",
                'algorithm = "ed25519"',
                f'public_key_hex = "{site_key.public_key_hex}"',
                'status = "ACTIVE"',
                f'purpose = "{site_key.purpose}"',
                "",
                "[keys.compute-profile-v2]",
                'algorithm = "ed25519"',
                f'public_key_hex = "{compute_public}"',
                'status = "ACTIVE"',
                'purpose = "compute-profile-qualification"',
                "",
            )
        ),
        encoding="utf-8",
    )
    return (
        profile_path,
        receipt_path,
        tmp_path / "evidence" / "site_receipts",
        trust_store_path,
        registry_path,
    )


@pytest.mark.parametrize("status", ["Stopped", "Failed", "Unknown"])
def test_cli_main_compute_qualify_blocks_non_deleted_fake_instances(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
    monkeypatch: pytest.MonkeyPatch,
    status: str,
) -> None:
    profile, receipt, site_receipts, trust_store, registry = _cli_fixture(tmp_path)
    name, remark = make_ownership_marker(f"cli-live-{status.lower()}")
    runner = FakeCompShareCliRunner(initial_stock=0)
    runner.instances["inst-cli-live"] = {
        "id": "inst-cli-live",
        "instance_id": "inst-cli-live",
        "name": name,
        "remark": remark,
        "status": status,
    }

    real_cli_class = compshare_cli_module.CompShareCli

    def fake_cli_factory(*args, **kwargs):
        return real_cli_class(runner=runner)

    # The CLI entry and its live checker remain real; only the official CLI
    # subprocess boundary is supplied with a credential-free Fake runner.
    monkeypatch.setattr(compshare_cli_module, "CompShareCli", fake_cli_factory)
    code = cli.main(
        [
            "compute",
            "qualify",
            "--profile",
            str(profile),
            "--receipt",
            str(receipt),
            "--site-receipts-dir",
            str(site_receipts),
            "--trust-store",
            str(trust_store),
            "--site-profile-registry",
            str(registry),
        ]
    )

    assert code == 2
    assert "live cloud query detected active instances" in capsys.readouterr().err


def test_cli_main_compute_qualify_fails_closed_on_managed_empty_id(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    profile, receipt, site_receipts, trust_store, registry = _cli_fixture(tmp_path)
    name, remark = make_ownership_marker("cli-live-empty-id")
    runner = FakeCompShareCliRunner(initial_stock=0)
    runner.instances["provider-record-without-id"] = {
        "id": "",
        "instance_id": "",
        "name": name,
        "remark": remark,
        "status": "Running",
    }
    real_cli_class = compshare_cli_module.CompShareCli
    monkeypatch.setattr(
        compshare_cli_module,
        "CompShareCli",
        lambda *args, **kwargs: real_cli_class(runner=runner),
    )

    code = cli.main(
        [
            "compute",
            "qualify",
            "--profile",
            str(profile),
            "--receipt",
            str(receipt),
            "--site-receipts-dir",
            str(site_receipts),
            "--trust-store",
            str(trust_store),
            "--site-profile-registry",
            str(registry),
        ]
    )

    assert code == 2
    assert "empty instance_id" in capsys.readouterr().err
