#!/usr/bin/env python3
"""
Independent structure parser for the HIDDEN expert initial structure (Acceptance
Board A1).  The case is coordinate-free: public/ holds only system.json, so the
parser fingerprints the hidden reference structure, never a public coordinate.

Reads reference/expert-trajectory/initial/water64.xyz and emits
source/structure-parse.json:
- atom count / element counts (must be 192 / O=64 / H=128)
- cell lengths from the file (PACKMOL header "cell = ...")
- first/last atom lines, all-finite check
- per-species coordinate bounds (informational)

Pure standard library + no third-party deps so it can be re-run anywhere.
Output is deterministic (sorted keys, fixed precision), so sha256 of
structure-parse.json is a re-checkable fingerprint of the parsed structure.

Run:  python3 source/structure_parse.py
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
XYZ = ROOT / "reference" / "expert-trajectory" / "initial" / "water64.xyz"
# Relative (not absolute) input path, so the fingerprint is machine-independent.
XYZ_REL = "reference/expert-trajectory/initial/water64.xyz"
OUT = HERE / "structure-parse.json"


def parse_xyz(path: Path) -> dict:
    with open(path) as fh:
        lines = fh.readlines()

    n_header = int(lines[0].split()[0])
    comment = lines[1].strip()
    atoms = [l.split() for l in lines[2:] if l.strip()]
    if len(atoms) != n_header:
        raise ValueError(f"header says {n_header} atoms, file has {len(atoms)}")

    counts: dict[str, int] = {}
    bounds: dict[str, list] = {}
    all_finite = True
    first = None
    last = None
    for row in atoms:
        sym = row[0]
        try:
            xyz = [float(v) for v in row[1:4]]
        except (ValueError, IndexError) as exc:
            raise ValueError(f"bad coord line: {row!r}") from exc
        if not all(abs(v) < 1e300 for v in xyz):
            all_finite = False
        counts[sym] = counts.get(sym, 0) + 1
        b = bounds.setdefault(sym, [1e300, 1e300, 1e300, -1e300, -1e300, -1e300])
        for i, v in enumerate(xyz):
            b[i] = min(b[i], v)
            b[i + 3] = max(b[i + 3], v)
        if first is None:
            first = row
        last = row

    # PACKMOL xyz header: "generated by PACKMOL ... cell = <a> <b> <c> ..." or
    # "cell = ..." in the comment line; fall back to 12.4 defaults only if the
    # header carries nothing parseable.
    cell = None
    import re
    m = re.search(r"cell\s*=\s*([0-9.]+)\s+([0-9.]+)\s+([0-9.]+)", comment, re.I)
    if m:
        cell = [float(m.group(i)) for i in (1, 2, 3)]
    if cell is None:
        # also accept "a=b=c=" style
        m = re.search(r"[Aa]=\s*([0-9.]+)\s+[Bb]=\s*([0-9.]+)\s+[Cc]=\s*([0-9.]+)", comment)
        if m:
            cell = [float(m.group(i)) for i in (1, 2, 3)]

    return {
        "natoms_header": n_header,
        "natoms_parsed": len(atoms),
        "comment": comment,
        "element_counts": {k: counts[k] for k in sorted(counts)},
        "cell_angstrom": cell,
        "coords_all_finite": all_finite,
        "per_species_bounds_A": {k: bounds[k] for k in sorted(bounds)},
        "first_atom": first,
        "last_atom": last,
    }


def main() -> int:
    result = parse_xyz(XYZ)
    body = json.dumps(result, indent=2) + "\n"
    OUT.write_text(body)
    h = hashlib.sha256(body.encode()).hexdigest()
    doc = {
        "benchmark_id": "034-ai2kit-water64-end-to-end-potential",
        "role": "independent_structure_parse",
        "input": XYZ_REL,
        "input_sha256": _sha256(XYZ),
        "parsed": result,
        "output_sha256": h,
    }
    OUT.write_text(json.dumps(doc, indent=2) + "\n")
    print(f"wrote {OUT} (sha256 {h})")
    ok = result["natoms_parsed"] == 192 and result["element_counts"] == {"H": 128, "O": 64}
    print("expectation 192/64/128:", "PASS" if ok else "FAIL")
    return 0 if ok else 1


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


if __name__ == "__main__":
    sys.exit(main())
