"""Shared MLP plugins for ``hpc_controller`` cases (Task 16).

A plugin is the *scientific* translation layer between a case's declared
runtime requirements / ``scientific_capabilities`` and the remote compute
command a Candidate submits through the common Gateway.  It is shared across
the five HPC cases and selected by capability, never by case id.

A plugin owns only capability/scientific translation:

* ``serves`` — does this plugin satisfy a declared runtime requirement or
  scientific capability?
* ``build_canary_job`` — a declared, capability-owning *canary* job the
  harness may submit to prove the common gateway path (submit → wait →
  fetch → settle) end-to-end.  The canary command is a fixed, safe argv: it
  carries **no case id**, **no hidden ``solution/`` path**, and does **not**
  masquerade as a scientific workflow.  It only proves the transport.

A plugin never stages a hidden ``solution/``, never carries scheduler policy
(account/partition/QoS/gres — those live in the site profile and Gateway),
and never receives a case id as a dispatch parameter.  Formal job commands
are Candidate-authored and validated by the Gateway schema/allowlist, not
generated here.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Protocol

from ccbench.contracts.case import CaseSpec, RuntimeRequirement

# The canary's declared output: a plain-text marker in the job's workdir that
# the fake/process adapter's ``fetch`` returns (it only surfaces ``.txt``).
_CANARY_OUTPUT = "canary.txt"


class MLPPluginError(ValueError):
    """No plugin can translate the case's requirements / capabilities."""


@dataclass(frozen=True)
class MLPPlugin:
    """One shared MLP category plugin.

    ``category`` is the dotted plugin identity (``mlp.matclaw-cips``).
    ``capabilities`` is the set of scientific requirement *names* this plugin
    serves.  Neither is a case id; selection is purely by capability.
    """

    category: str
    capabilities: tuple[str, ...]

    def serves(self, requirement: RuntimeRequirement) -> bool:
        """True when this plugin satisfies a declared runtime requirement."""
        return requirement.name in self.capabilities


# --------------------------------------------------------------------------- #
# Registry + selection (by capability, never by case id)
# --------------------------------------------------------------------------- #

PLUGINS: tuple[MLPPlugin, ...] = (
    MLPPlugin("mlp.matclaw-cips", ("matclaw-cips",)),
    MLPPlugin("mlp.ai2kit-water", ("ai2kit",)),
    MLPPlugin("mlp.deepmd-jax-go-water", ("dpmp",)),
    MLPPlugin("mlp.generic", ("cp2k", "deepmd-kit", "ase-rdkit", "mace", "xtb")),
)


def select_mlp_plugin(spec: CaseSpec) -> MLPPlugin:
    """Resolve the plugin for a case from its requirements/capabilities.

    Selection is by declared runtime requirements, then by
    ``scientific_capabilities`` for HPC cases.  Case id is never consulted.
    """
    declared = list(spec.runtime_requirements)
    if spec.scientific_capabilities is not None:
        for name in spec.scientific_capabilities.required:
            declared.append(RuntimeRequirement(name=name))
    for requirement in declared:
        for plugin in PLUGINS:
            if plugin.serves(requirement):
                return plugin
    raise MLPPluginError(
        f"no MLP plugin serves requirements/capabilities "
        f"{[r.name for r in declared]}; register a capability in "
        f"ccbench/plugins/mlp.PLUGINS"
    )


# --------------------------------------------------------------------------- #
# Canary job builder
# --------------------------------------------------------------------------- #

# Fixed, safe canary argv: writes a plain marker into the job workdir.  No
# case id, no hidden solution path, no scientific entry point — it proves only
# that the declared command reaches the compute runtime and its output is
# fetched.  ``/bin/sh -c`` keeps it portable across the fake and local
# adapters; the real site's compute command is Candidate-authored.
CANARY_COMMAND = ("/bin/sh", "-c", "printf 'declared-canary\\n' > canary.txt")


def build_canary_job(
    spec: CaseSpec,
    *,
    run_id: str,
    operation_id: str,
    runtime: str,
    resources: dict[str, int],
    environment: dict[str, str] | None = None,
) -> dict[str, Any]:
    """Build a declared, capability-owning canary ``job.yaml`` (a JobSpec dict).

    The command is the fixed, safe :data:`CANARY_COMMAND` — never derived from
    the case id and never referencing a hidden solution.  ``runtime`` is the
    resolved compute runtime identity; ``outputs`` names the marker the
    Gateway fetches.  Formal Candidate jobs are validated by the Gateway
    schema/allowlist, not generated by a plugin.
    """
    select_mlp_plugin(spec)  # fail closed if no capability serves this case
    return {
        "schema_version": 1,
        "idempotency_key": f"{run_id}:{operation_id}",
        "runtime": runtime,
        "command": list(CANARY_COMMAND),
        "resources": dict(resources),
        "environment": dict(environment or {}),
        "inputs": [],
        "outputs": [_CANARY_OUTPUT],
    }


def canary_output() -> str:
    return _CANARY_OUTPUT
